language: ruby

install:
  - sudo apt-get install snapd
  - sudo snap install hugo
  - sudo gem install jekyll
  - git clone git@github.com:thiagohersan/atibaia.alab.space.git

script:
    - cd atibaia.alab.space
    - ./deploy.sh

after_script:
  - cd ..
  - rm -rf atibaia.alab.space
