baseurl = "http://atibaia.flab.space/"
languageCode = "en-us"
title = "Festival de Arte e Tecnologia de Atibaia 2016"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source)

	# To provide some metadata for search engines
	name = "Festival de Arte e Tecnologia de Atibaia 2016"
	description = "Festival de Arte e Tecnologia de Atibaia 2016 - Incubadora de Artistas"

	# The path must be relative to the static folder
	favicon = "beijo.png"

	# Navigation
	[params.navigation]
		brand = "⬆"

		[params.navigation.links]
			about    = "Festival"
			projects = "Projetos"
			artists  = "Participantes"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace './static/img/header.jpg'
		slogan     = "Festival de Arte e Tecnologia"
		subtitle   = "2 Julho - 10 Outubro 2016<br />Atibaia, SP"
		buttonText = "Find out more"



    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"
