name: build site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
          sudo dpkg -i hugo_0.19-64bit.deb

      - name: Build
        run: |
          if [ ! -d themes ]; then
            mkdir themes
            pushd themes
            git clone https://github.com/digitalcraftsman/hugo-creative-theme.git
            popd
          fi
          hugo -d public

      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Dispatch
        run: |
          curl -X POST \
          -u "${{ secrets.PUSH_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/thiagohersan-www/atibaia.alab.space/dispatches \
          --data '{"event_type":"build-site"}'

# curl -X POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/dispatches --data '{"event_type": "build_application"}'
# curl -X POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'
# curl -X POST -u "${{ secrets.PUSH_TOKEN }}"                         -H 'Accept: application/vnd.github.everest-preview+json'                                     https://api.github.com/repos/:userName/:repoName/dispatches --data '{"event_type": "Trigger Workflow" }'