name: build site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
          sudo dpkg -i hugo_0.19-64bit.deb

      - name: Build
        run: |
          if [ ! -d themes ]; then
            mkdir themes
            pushd themes
            git clone https://github.com/digitalcraftsman/hugo-creative-theme.git
            popd
          fi
          hugo -d public

      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Dispatch
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PUSH_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/thiagohersan-www/atibaia.alab.space/dispatches \
          -d '{"event_type":"build-site"}'
